import '@testing-library/jest-dom'

// Mock electronAPI for tests
window.electronAPI = {
  login: async () => ({ success: false, error: 'Mock: Not implemented' }),
  logout: async () => ({ success: true }),
  getSession: async () => ({ success: false, data: null }),
  unlock: async () => ({ success: false, error: 'Mock: Not implemented' }),
  listProducts: async () => ({ success: true, data: [] }),
  searchProducts: async () => ({ success: true, data: [] }),
  createProduct: async () => ({ success: true, data: { id: 'mock', code: 'MOCK', name: 'Mock', type: 'PRODUCT', price: 0, priceUsd: 0, stock: 0, active: true, taxes: [] } }),
  updateProduct: async () => ({ success: true, data: { id: 'mock', code: 'MOCK', name: 'Mock', type: 'PRODUCT', price: 0, priceUsd: 0, stock: 0, active: true, taxes: [] } }),
  deleteProduct: async () => ({ success: true }),
  listCategories: async () => ({ success: true, data: [{ id: '1', name: 'General', color: '#3b82f6' }] }),
  createCategory: async () => ({ success: true, data: { id: '1', name: 'Nueva', color: '#3b82f6' } }),
  updateCategory: async () => ({ success: true, data: { id: '1', name: 'Editada', color: '#10b981' } }),
  deleteCategory: async () => ({ success: true }),
  listTaxes: async () => ({ success: true, data: [{ id: '1', name: 'IVA 16%', rate: 16, active: true }] }),
  createTax: async () => ({ success: true, data: { id: '1', name: 'IVA 16%', rate: 16, active: true } }),
  updateTax: async () => ({ success: true, data: { id: '1', name: 'IVA 16%', rate: 16, active: true } }),
  createSale: async () => ({ success: true, data: {
    id: 'mock', receiptNumber: 1, documentType: 'TICKET', status: 'COMPLETED', subtotal: 100, taxTotal: 16,
    discount: 0, total: 116, payments: [{ id: 'p1', method: 'CASH', amountBs: 116 }], usdRate: 50, userId: '1',
    customerId: null, customer: null, items: [], notes: null, createdAt: new Date().toISOString()
  } }),
  listSales: async () => ({ success: true, data: [] }),
  cancelSale: async () => ({ success: true, data: {
    id: 'mock', receiptNumber: 1, documentType: 'TICKET', status: 'CANCELLED', subtotal: 100, taxTotal: 16,
    discount: 0, total: 116, payments: [{ id: 'p1', method: 'CASH', amountBs: 116 }], usdRate: 50, userId: '1',
    customerId: null, customer: null, items: [], notes: null, createdAt: new Date().toISOString()
  } }),
  getNextReceiptNumber: async () => ({ success: true, data: 42 }),
  getUsdRate: async () => ({ success: false, error: 'Mock: Not implemented' }),
  getUsdRateHistory: async () => ({ success: true, data: [] }),
  getConfig: async () => ({ success: false, error: 'Mock: Not implemented' }),
  updateConfig: async () => ({ success: false, error: 'Mock: Not implemented' }),
  testPrinter: async () => ({ success: false, error: 'Mock: Not implemented' }),
  printReceipt: async () => ({ success: false, error: 'Mock: Not implemented' }),
  getFiscalConfig: async () => ({ success: true, data: { printerType: 'bixolon', printerPort: 'COM1', printerEnabled: false, seniatEnabled: false, autoSendSeniat: false } }),
  updateFiscalConfig: async () => ({ success: true }),
  listUsers: async () => ({ success: true, data: [] }),
  createUser: async () => ({ success: false, error: 'Mock: Not implemented' }),
  updateUser: async () => ({ success: false, error: 'Mock: Not implemented' }),
  toggleUserActive: async () => ({ success: false, error: 'Mock: Not implemented' }),
  listRoles: async () => ({ success: true, data: [] }),
  createRole: async () => ({ success: false, error: 'Mock: Not implemented' }),
  updateRole: async () => ({ success: false, error: 'Mock: Not implemented' }),
  deleteRole: async () => ({ success: false, error: 'Mock: Not implemented' }),
  listPermissions: async () => ({ success: true, data: [] }),
  listCustomers: async () => ({ success: true, data: [] }),
  searchCustomers: async () => ({ success: true, data: [] }),
  findCustomerByTaxId: async () => ({ success: true, data: null }),
  createCustomer: async () => ({ success: true, data: { id: '1', taxId: 'J-12345678-4', name: 'Mock', active: true } }),
  updateCustomer: async () => ({ success: true, data: { id: '1', taxId: 'J-12345678-4', name: 'Mock', active: true } }),
  deleteCustomer: async () => ({ success: true }),
  getCompanyConfig: async () => ({ success: true, data: { businessName: '', taxId: null, address: null, phone: null, email: null, logo: null } }),
  updateCompanyConfig: async () => ({ success: true, data: { businessName: 'Empresa', taxId: null, address: null, phone: null, email: null, logo: null } }),
  openRegister: async () => ({ success: true, data: { id: 'reg-1' } }),
  closeRegister: async () => ({ success: true }),
  getCashSummary: async () => ({ success: true, data: { register: null, sales: [] } }),
  addCashMovement: async () => ({ success: true }),
  getDailyReport: async () => ({ success: true, data: { date: new Date().toISOString(), sales: 0, total: 0, byMethod: {} } }),
  getProductReport: async () => ({ success: true, data: [] }),
  getUserReport: async () => ({ success: true, data: [] }),
  getIvaReport: async () => ({ success: true, data: { period: '2026-07', entries: [], totals: { subtotal: 0, taxTotal: 0, total: 0, discount: 0 } } }),
  listPlugins: async () => ({ success: true, data: [] }),
  installPlugin: async () => ({ success: false, error: 'Mock: Not implemented' }),
  togglePluginActive: async () => ({ success: true, data: { active: true } }),

  // Kernel / Country Plugin
  getCountryPlugin: async () => ({ success: true, data: null }),
  getCountryConfig: async () => ({ success: true, data: { country: 'VE' } })
} as unknown as Window['electronAPI']
