import '@testing-library/jest-dom'

// Mock electronAPI for tests
window.electronAPI = {
  login: async () => ({ success: false, error: 'Mock: Not implemented' }),
  logout: async () => ({ success: true }),
  getSession: async () => ({ success: false, data: null }),
  listProducts: async () => ({ success: true, data: [] }),
  searchProducts: async () => ({ success: true, data: [] }),
  createProduct: async () => ({ success: true, data: { id: 'mock', code: 'MOCK', name: 'Mock', type: 'PRODUCT', price: 0, priceUsd: 0, stock: 0, active: true, taxes: [] } }),
  updateProduct: async () => ({ success: true, data: { id: 'mock', code: 'MOCK', name: 'Mock', type: 'PRODUCT', price: 0, priceUsd: 0, stock: 0, active: true, taxes: [] } }),
  deleteProduct: async () => ({ success: true }),
  listCategories: async () => ({ success: true, data: [{ id: '1', name: 'General', color: '#3b82f6' }] }),
  createCategory: async () => ({ success: true, data: { id: '1', name: 'Nueva', color: '#3b82f6' } }),
  updateCategory: async () => ({ success: true, data: { id: '1', name: 'Editada', color: '#10b981' } }),
  deleteCategory: async () => ({ success: true }),
  listTaxes: async () => ({ success: true, data: [{ id: '1', name: 'IVA 16%', rate: 16, active: true }] }),
  createTax: async () => ({ success: true, data: { id: '1', name: 'IVA 16%', rate: 16, active: true } }),
  updateTax: async () => ({ success: true, data: { id: '1', name: 'IVA 16%', rate: 16, active: true } }),
  createSale: async () => ({ success: true, data: {
    id: 'mock', receiptNumber: 1, status: 'COMPLETED', subtotal: 100, taxTotal: 16, total: 116,
    paymentMethod: 'CASH', usdRate: 50, userId: '1', customerId: null, items: [], createdAt: new Date().toISOString()
  } }),
  listSales: async () => ({ success: false, error: 'Mock: Not implemented' }),
  cancelSale: async () => ({ success: false, error: 'Mock: Not implemented' }),
  openRegister: async () => ({ success: false, error: 'Mock: Not implemented' }),
  closeRegister: async () => ({ success: false, error: 'Mock: Not implemented' }),
  getCashSummary: async () => ({ success: false, error: 'Mock: Not implemented' }),
  getUsdRate: async () => ({ success: false, error: 'Mock: Not implemented' }),
  getConfig: async () => ({ success: false, error: 'Mock: Not implemented' }),
  updateConfig: async () => ({ success: false, error: 'Mock: Not implemented' }),
  testPrinter: async () => ({ success: false, error: 'Mock: Not implemented' }),
  printReceipt: async () => ({ success: false, error: 'Mock: Not implemented' }),
  listUsers: async () => ({ success: true, data: [] }),
  createUser: async () => ({ success: false, error: 'Mock: Not implemented' }),
  updateUser: async () => ({ success: false, error: 'Mock: Not implemented' }),
  toggleUserActive: async () => ({ success: false, error: 'Mock: Not implemented' }),
  listCustomers: async () => ({ success: true, data: [] }),
  searchCustomers: async () => ({ success: true, data: [] }),
  findCustomerByTaxId: async () => ({ success: true, data: null }),
  createCustomer: async () => ({ success: true, data: { id: '1', taxId: 'J-12345678-4', name: 'Mock', active: true } }),
  updateCustomer: async () => ({ success: true, data: { id: '1', taxId: 'J-12345678-4', name: 'Mock', active: true } }),
  deleteCustomer: async () => ({ success: true }),
  listPlugins: async () => ({ success: true, data: [] }),
  installPlugin: async () => ({ success: false, error: 'Mock: Not implemented' }),
  togglePluginActive: async () => ({ success: true, data: { active: true } })
} as unknown as Window['electronAPI']
